---
title: "Project-DATA"
author: "Theo Schouten"
date: "2025-09-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
library(tidyverse)
library(dplyr)
library(jsonlite)
library(readxl)
library(psych)   
library(ggplot2)
library(corrplot)

df_1 = read.csv("https://ourworldindata.org/grapher/expected-years-of-schooling.csv?v=1&csvType=filtered&useColumnShortNames=true&mapSelect=CHN~NOR~SWE~FIN~CAN~USA~RUS~DEU~NLD~DNK~IRL~ISL~GBR~ESP~FRA~ITA~MEX~IND~BFA~MLI~DZA~TCD~ZAF~RWA~COD~PRY~BRA~PER~COL~AUS~NZL~PNG~PAK&overlay=download-data")

df_2 = read.csv("https://ourworldindata.org/grapher/average-years-of-schooling.csv?v=1&csvType=filtered&useColumnShortNames=true&mapSelect=CAN~USA~MEX~RUS~CHN~GBR~IRL~ISL~AND~ESP~FRA~DEU~DNK~NLD~ITA~BFA~RWA~COD~ZAF~SOM~TCD~DZA~MLI~AUS~PNG~NZL~BRA~PER~COL~NOR~FIN~SWE&overlay=download-data")

df_3 = read.csv("https://ourworldindata.org/grapher/total-government-expenditure-on-education-gdp.csv?v=1&csvType=filtered&useColumnShortNames=true&mapSelect=CAN~USA&overlay=download-data")

df_4 = read.csv("https://ourworldindata.org/grapher/schools-access-drinking-water.csv?v=1&csvType=full&useColumnShortNames=true")

df_5 = read.csv("https://ourworldindata.org/grapher/human-rights-index-vdem.csv?v=1&csvType=full&useColumnShortNames=true")

df_5 = df_5 %>%
  group_by(Entity) %>%
  mutate(mean_human_rights = mean(civ_libs_vdem__estimate_best, na.rm = TRUE))

df_6 = read.csv("world_population.csv")

df_6 = df_6 %>%
  rename(Entity = Country.Territory) 

df_6 = df_6[,c("Entity", "Density..per.km.." )]

df_7 = read_excel("publications.xlsx")

df_7 = df_7 %>%
  rename(Entity = Country) 

df_7 = df_7[,c("Entity","Citations per document")]
#load up on economic data to predict mys
#gini index wealth disparity

df_8 = merge(df_1,df_2,all = TRUE)
df_9 = merge(df_3,df_4,all = TRUE)
df_10 = merge(df_5,df_6,all = TRUE)
df_11 = merge(df_7, df_8, all = TRUE)
df_12 = merge(df_9, df_10, all = TRUE)
df_13 = merge(df_11, df_12, all = TRUE)


final = df_13 %>%
  group_by(Entity) %>%
  summarise(across(everything(), ~ first(na.omit(.)))) %>%
  drop_na() %>%
   dplyr::select(-Code, -Year, -time.1, -time, -owid_region, -civ_libs_vdem__estimate_best)

final = final %>%
  rename(expected_schooling = eys__sex_total, mean_schooling = mys__sex_total, GDP_share = combined_expenditure_share_gdp, primary_water = X_4_a_1__se_acs_h2o__primary, upper_secondary_water = X_4_a_1__se_acs_h2o__upper_secondary, lower_secondary_water = X_4_a_1__se_acs_h2o__lower_secondary, mean_rights = mean_human_rights, density_per_km = Density..per.km..)

final


# Visualize and use describe() to present descriptive statistics for each dimension

# Visualize and summarize the covariability between each pair of dimensions

# Identify potential two-dimensional outliers and investigate their influence
```

```{r}
numeric_final = final[,-c(1)]

describe(final)
#Group by Entity/ Country and find all plots

ggplot(data = final, aes(x = Entity, y = `Citations per document`)) +
  geom_point() 
ggplot(data = final, aes(x = Entity, y = `expected_schooling`)) +
  geom_point() 
ggplot(data = final, aes(x = Entity, y = `mean_schooling`)) +
  geom_point() 
ggplot(data = final, aes(x = Entity, y = `GDP_share`)) +
  geom_point() 
ggplot(data = final, aes(x = Entity, y = `primary_water`)) +
  geom_point() 
ggplot(data = final, aes(x = Entity, y = `lower_secondary_water`)) +
  geom_point() 
ggplot(data = final, aes(x = Entity, y = `upper_secondary_water`)) +
  geom_point() 
ggplot(data = final, aes(x = Entity, y = `mean_rights`)) +
  geom_point() 
ggplot(data = final, aes(x = Entity, y = `density_per_km`)) +
  geom_point() 
```

```{r}

pairs(numeric_final, pch= 16)

corrplot(cor(numeric_final, use = "complete.obs"), method = "square")

cor(numeric_final)

```

```{r}
mahalanobis_distances = mahalanobis(numeric_final, colMeans(numeric_final), cov(numeric_final))
df = ncol(numeric_final)
cutoff_value = qchisq(1 - 0.05, df)

outliers = which(mahalanobis_distances > cutoff_value)
outliers
```

```{r}

final[c(9,33,51,56,57,60,62,74,75), ]

colMeans(numeric_final)

# Creating comparison dataframe

# bounds
mean_vals = colMeans(numeric_final)
sd_vals = apply(numeric_final, 2, sd)
upper_bound = mean_vals + 2 * sd_vals
lower_bound = mean_vals - 2 * sd_vals

# Create comparison with bounds
comparison = rbind(numeric_final[c(9,33,51,56,57,60,62,74,75), ], mean_vals, upper_bound, lower_bound)
comparison = as.data.frame(comparison)
rownames(comparison)[10:12] = c("Mean", "Mean+2SD", "Mean-2SD")
comparison
view(comparison)

```

```{r}
#where outliers are coming from

#1st one is Barbados, 
#High citations (45.18) + high density (655) + maximum water access + high education

#2 is Honduras
#Moderate citations but low expected schooling (10.16) relative to other metrics
#Unusual combination of research output with lower educational expectations

#3 is Mexico 
#Good expected schooling (14.47) but mixed water access (49-76%)
#Educational expectations don't match infrastructure reality

#4 Nicaragua
#severely deficient water infrastructure

#5 Niger
#Extremely low mean schooling (1.41)
#moderate expected schooling (8.31) and GDP share (4.07)
#low pop density (20.69)
#Huge gap between actual and expected education

#6 Pakistan
#low GDP share (1.88), as expected low schooling (7.90 (expected), 4.32 (mean) )
#Poor water access across all levels (28-52%)

#7 Panama
#Very high citations (38.37) 
#poor secondary water access (37-46%)

#8 Sierra Leone
#Massive GDP share (8.54) but low education (9.06, 3.54)

#9 Singapore
#Extreme density (8416) caused by being a city state
#high education + high citations


#Some of these make sense and should be kept but some are unreasonable and should be throw away, more analysis needed.
```

```{r}
cor_outlier = cor(numeric_final)
cor_without = cor(numeric_final[-outliers, ])
cor_difference = cor_outlier - cor_without

cor_difference

#mostly changes cor between citations and water
#also changes density with schooling, probably because of singapore
```


Start EFA work here
```{r}
#Response varaibles are expected schooling, mean rights, GDP_share [,3], [,5], [,9]

#predictor varaibles are everything else

final_matrix_response = as.matrix(final[,c(3,5,9)])

R_response = cor(final_matrix_response)
eigen_response = eigen(R_response)

final_matrix_predictor = as.matrix(final[,-c(1,3,5,9)])

R_predictor = cor(final_matrix_predictor)
eigen_predictor = eigen(R_predictor)

plot(eigen_response$values, type = "b")
#No elbow exists
plot(eigen_predictor$values, type = "b")
#1

which(eigen_response$values > 1)
#1
which(eigen_predictor$values > 1)
#1

which(eigen_response$values > 0.7)
#2
which(eigen_predictor$values > 0.7)
#3

corrplot(R_response, method="color",order = "hclust")
corrplot(R_predictor, method="color",order = "hclust")

```




